fieldLayouts:
  85c44ad6-24ff-4174-807e-273c589e9eeb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 02eeba0a-bc61-4ac4-8094-01406e1c36e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9dbd0d22-26ff-460e-ae13-274b92cbb1d4 # rich text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c53528d1-7714-415e-b725-06e38655d4a6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 231e8678-599f-414d-85e0-b8bd35ad9888
        userCondition: null
handle: header
hasTitleField: false
name: header
section: 1ceba4de-d5a6-48d1-a45a-47306f11f334 # header
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
