fieldLayouts:
  1b073f92-068f-4a87-b2af-dc8bf6d5f62a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1445d322-a51e-4517-889c-ffd17e6fee8f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 878d00c8-bd36-49ef-8232-5e5a7c563249
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e825b7f2-aeeb-4d5e-9c68-b84f8a69750b
        userCondition: null
fs: assets
handle: newsAssets
name: 'news assets'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: assets
transformSubpath: ''
