columnSuffix: null
contentColumnType: string
fieldGroup: c97214b7-85d5-47b8-a947-5b4856161a02 # Common
handle: bannerImage
instructions: null
name: 'banner image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:bed4307a-1575-4687-9512-592539923a73' # news assets
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: thumbs
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:bed4307a-1575-4687-9512-592539923a73' # news assets
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\assets\FileSizeConditionRule
              -
                - uid
                - 9a988da2-8d09-4e3d-819f-f55851ecd3b3
              -
                - operator
                - '<'
              -
                - value
                - '100'
              -
                - maxValue
                - ''
              -
                - unit
                - MB
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
