defaultPlacement: end
enableVersioning: true
handle: footer
name: footer
propagationMethod: all
siteSettings:
  7bfc15e2-be19-4fa8-82e4-3b95a69c0ca2: # craft-news-b
    enabledByDefault: true
    hasUrls: true
    template: footer/_entry
    uriFormat: footer
type: single
