defaultPlacement: end
enableVersioning: true
handle: plugins
name: plugins
propagationMethod: all
siteSettings:
  7bfc15e2-be19-4fa8-82e4-3b95a69c0ca2: # craft-news-b
    enabledByDefault: true
    hasUrls: true
    template: plugins/_entry
    uriFormat: 'plugins/{slug}'
type: channel
